"""Data generation and loading helpers for ECG-TransCovNet."""

from __future__ import annotations

from pathlib import Path
from typing import Tuple

import numpy as np

from .simulator.conditions import Condition
from .simulator.ecg_simulator import ECGSimulator
from .constants import (
    NUM_CLASSES,
    CONDITION_TO_IDX,
    CLASS_NAMES,
    SIGNAL_LENGTH,
    MIT_BIH_PROPORTIONS,
)


def _pick_condition(
    rng: np.random.Generator,
    proportions: dict[Condition, float] | None = None,
) -> Condition:
    """Sample a condition according to *proportions* (uniform if None)."""
    if proportions:
        conditions = list(proportions.keys())
        weights = np.array([proportions[c] for c in conditions])
    else:
        conditions = list(Condition)
        weights = np.ones(len(conditions))
    weights = weights / weights.sum()
    return conditions[rng.choice(len(conditions), p=weights)]


_MIXED_NOISE_LEVELS = ["clean", "low", "medium"]


def generate_dataset(
    num_samples: int,
    leads: list[str],
    noise_level: str = "medium",
    proportions: dict[Condition, float] | None = None,
    seed: int = 42,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate ECG signals using the simulator.

    When *noise_level* is ``"mixed"``, each sample is generated with a
    randomly chosen noise level from clean / low / medium.

    Returns:
        signals: (N, num_leads, SIGNAL_LENGTH) float32
        labels:  (N,) int64
    """
    sim = ECGSimulator(seed=seed)
    signals = []
    labels = []

    for i in range(num_samples):
        condition = _pick_condition(sim._rng, proportions)
        if noise_level == "mixed":
            sample_noise = sim._rng.choice(_MIXED_NOISE_LEVELS)
        else:
            sample_noise = noise_level
        ecg = sim.generate_ecg(condition, noise_level=sample_noise)

        # Stack selected leads: (num_leads, 2400)
        signal = np.stack([ecg[lead] for lead in leads], axis=0)

        # Per-lead z-score normalisation
        for ch in range(signal.shape[0]):
            mu, std = signal[ch].mean(), signal[ch].std()
            if std > 1e-6:
                signal[ch] = (signal[ch] - mu) / std

        signals.append(signal.astype(np.float32))
        labels.append(CONDITION_TO_IDX[condition])

        if (i + 1) % 500 == 0:
            print(f"  Generated {i + 1}/{num_samples} samples...")

    return np.array(signals), np.array(labels, dtype=np.int64)


def load_or_generate_data(
    cache_dir: str,
    num_train: int,
    num_val: int,
    leads: list[str],
    noise_level: str,
    seed: int,
    distribution: str = "balanced",
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load cached data or generate new."""
    leads_tag = "-".join(leads)
    cache_path = (
        Path(cache_dir)
        / f"ecg_{leads_tag}_{noise_level}_{distribution}_t{num_train}_v{num_val}_s{seed}.npz"
    )

    if cache_path.exists():
        print(f"Loading cached data from {cache_path}")
        d = np.load(cache_path)
        return d["train_X"], d["train_y"], d["val_X"], d["val_y"]

    balanced = {c: 1.0 / NUM_CLASSES for c in Condition}

    if distribution == "mit_bih":
        train_props = MIT_BIH_PROPORTIONS
        desc = "MIT-BIH proportions"
    else:
        train_props = balanced
        desc = "balanced"

    print(f"Generating {num_train} training samples ({desc})...")
    train_X, train_y = generate_dataset(
        num_train, leads, noise_level, train_props, seed,
    )

    print(f"Generating {num_val} validation samples (balanced)...")
    val_X, val_y = generate_dataset(
        num_val, leads, noise_level, balanced, seed + 10000,
    )

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        cache_path, train_X=train_X, train_y=train_y, val_X=val_X, val_y=val_y,
    )
    print(f"Cached data to {cache_path}")
    return train_X, train_y, val_X, val_y


def load_hdf5_test_samples(
    test_dir: str,
    leads: list[str],
) -> list[Tuple[str, np.ndarray, int]]:
    """Load test samples from HDF5 files generated by generate_conditions_test_set.py.

    Returns:
        List of (label, signal, class_index) tuples.
    """
    import h5py

    # Map file label prefixes to Condition enum
    LABEL_TO_CONDITION = {
        "sinus_brady": Condition.SINUS_BRADYCARDIA,
        "normal_sinus": Condition.NORMAL_SINUS,
        "sinus_tachy": Condition.SINUS_TACHYCARDIA,
        "afib": Condition.ATRIAL_FIBRILLATION,
        "aflutter": Condition.ATRIAL_FLUTTER,
        "svt": Condition.SVT,
        "pvc": Condition.PVC,
        "vtach": Condition.VENTRICULAR_TACHYCARDIA,
        "lbbb": Condition.LBBB,
        "rbbb": Condition.RBBB,
        "avblock1": Condition.AV_BLOCK_1,
        "avblock2t1": Condition.AV_BLOCK_2_TYPE1,
        "ste": Condition.ST_ELEVATION,
    }

    test_path = Path(test_dir)
    if not test_path.exists():
        print(f"Warning: test directory {test_dir} does not exist")
        return []

    lead_order = ["ECG1", "ECG2", "ECG3", "aVR", "aVL", "aVF", "vVX"]
    samples = []

    for h5_file in sorted(test_path.glob("*.h5")):
        fname = h5_file.stem  # e.g. "afib_120_clean"

        # Find matching condition from prefix
        condition = None
        for prefix, cond in LABEL_TO_CONDITION.items():
            if fname.startswith(prefix):
                condition = cond
                break
        if condition is None:
            print(f"  Skipping {h5_file.name} (unknown condition)")
            continue

        class_idx = CONDITION_TO_IDX[condition]

        with h5py.File(h5_file, "r") as f:
            # Each file has event_1001
            for event_key in sorted(f.keys()):
                if not event_key.startswith("event_"):
                    continue
                event = f[event_key]
                if "ecg" not in event:
                    continue

                ecg_group = event["ecg"]
                # Stack leads
                lead_arrays = []
                for lead in leads:
                    if lead in ecg_group:
                        lead_arrays.append(ecg_group[lead][:])
                    else:
                        # Try matching from lead_order
                        idx = lead_order.index(lead) if lead in lead_order else -1
                        if idx >= 0 and str(idx) in ecg_group:
                            lead_arrays.append(ecg_group[str(idx)][:])
                        else:
                            lead_arrays.append(np.zeros(SIGNAL_LENGTH, dtype=np.float32))

                signal = np.stack(lead_arrays, axis=0)

                # Per-lead z-score (same as training)
                for ch in range(signal.shape[0]):
                    mu, std = signal[ch].mean(), signal[ch].std()
                    if std > 1e-6:
                        signal[ch] = (signal[ch] - mu) / std

                samples.append((fname, signal.astype(np.float32), class_idx))

    return samples


import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, TensorDataset


class AugmentedECGDataset(Dataset):
    """Wrapper that applies on-the-fly augmentation to an ECG dataset.

    Augmentations (training only):
      - Random circular time shift (up to ±max_shift samples)
      - Random per-channel amplitude scaling (scale_range)
      - Additive Gaussian noise (noise_std range)
      - Random channel dropout (zero one lead with prob channel_drop_prob)
    """

    def __init__(
        self,
        dataset: TensorDataset,
        max_shift: int = 200,
        scale_range: tuple[float, float] = (0.8, 1.2),
        noise_std_range: tuple[float, float] = (0.01, 0.05),
        channel_drop_prob: float = 0.1,
    ):
        self.dataset = dataset
        self.max_shift = max_shift
        self.scale_range = scale_range
        self.noise_std_range = noise_std_range
        self.channel_drop_prob = channel_drop_prob

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        signal, label = self.dataset[idx]
        signal = signal.clone()

        # Random circular time shift
        shift = torch.randint(-self.max_shift, self.max_shift + 1, (1,)).item()
        if shift != 0:
            signal = torch.roll(signal, shifts=shift, dims=-1)

        # Random per-channel amplitude scaling
        num_channels = signal.shape[0]
        lo, hi = self.scale_range
        scales = torch.empty(num_channels, 1).uniform_(lo, hi)
        signal = signal * scales

        # Additive Gaussian noise
        lo_n, hi_n = self.noise_std_range
        noise_std = torch.empty(1).uniform_(lo_n, hi_n).item()
        signal = signal + torch.randn_like(signal) * noise_std

        # Random channel dropout (zero out 1 lead)
        if num_channels > 1 and torch.rand(1).item() < self.channel_drop_prob:
            ch = torch.randint(0, num_channels, (1,)).item()
            signal[ch] = 0.0

        return signal, label


@torch.no_grad()
def evaluate_hdf5_test(
    model: torch.nn.Module,
    test_dir: str,
    leads: list[str],
    device: torch.device,
) -> None:
    """Evaluate trained model on HDF5 test files and print per-sample results."""
    model.eval()
    samples = load_hdf5_test_samples(test_dir, leads)
    if not samples:
        print(f"No test samples found in {test_dir}")
        return

    print(f"\n=== HDF5 Test Evaluation ({len(samples)} samples from {test_dir}) ===")
    print(f"  {'File':<30s} {'True Label':<28s} {'Predicted':<28s} {'Conf':>6s} {'Match':>5s}")
    print("  " + "-" * 99)

    correct = 0
    for fname, signal, true_idx in samples:
        x = torch.from_numpy(signal).unsqueeze(0).to(device)
        logits = model(x)
        probs = F.softmax(logits, dim=-1)[0]
        pred_idx = probs.argmax().item()
        conf = probs[pred_idx].item()
        match = pred_idx == true_idx
        if match:
            correct += 1

        true_name = CLASS_NAMES[true_idx]
        pred_name = CLASS_NAMES[pred_idx]
        mark = "OK" if match else "MISS"
        print(f"  {fname:<30s} {true_name:<28s} {pred_name:<28s} {conf:6.3f} {mark:>5s}")

    acc = correct / len(samples) if samples else 0
    print(f"\n  Test accuracy: {correct}/{len(samples)} = {acc:.1%}")
