#!/usr/bin/env python3
"""Visualize events from an HDF5 file generated by the ECG simulator.

Displays the 7-lead ECG waveform, PPG, respiratory signal, and vitals
for one or more events in a file.

Usage:
    # Show all events in a file (interactive matplotlib window)
    python scripts/visualize_hdf5.py data/inference/PT1234_2026-02.h5

    # Show a specific event
    python scripts/visualize_hdf5.py data/inference/PT1234_2026-02.h5 --event 1001

    # Show multiple events
    python scripts/visualize_hdf5.py data/inference/PT1234_2026-02.h5 --event 1001 1003

    # Save to PNG files instead of showing
    python scripts/visualize_hdf5.py data/inference/PT1234_2026-02.h5 --save-dir plots/

    # List events in a file without plotting
    python scripts/visualize_hdf5.py data/inference/PT1234_2026-02.h5 --list
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

# Sampling rates (must match simulator constants)
FS_ECG = 200.0
FS_PPG = 75.0
FS_RESP = 33.33

LEAD_NAMES = ["ECG1", "ECG2", "ECG3", "aVR", "aVL", "aVF", "vVX"]

# Condition value → human-readable name
_CONDITION_NAMES = {
    "N": "NORMAL_SINUS", "SB": "SINUS_BRADYCARDIA", "ST": "SINUS_TACHYCARDIA",
    "AFIB": "ATRIAL_FIBRILLATION", "AFL": "ATRIAL_FLUTTER", "A": "PAC",
    "SVTA": "SVT", "V": "PVC", "VT": "VENTRICULAR_TACHYCARDIA",
    "VF": "VENTRICULAR_FIBRILLATION", "L": "LBBB", "R": "RBBB",
    "1AVB": "AV_BLOCK_1", "2AVB1": "AV_BLOCK_2_TYPE1",
    "2AVB2": "AV_BLOCK_2_TYPE2", "STE": "ST_ELEVATION",
}


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Visualize ECG events from an HDF5 file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("file", type=str, help="Path to HDF5 file.")
    p.add_argument(
        "--event", type=int, nargs="+", default=None, metavar="ID",
        help="Event ID(s) to visualize (e.g. 1001 1002). Default: all events.",
    )
    p.add_argument(
        "--save-dir", type=str, default=None,
        help="Save plots to this directory as PNG files instead of showing.",
    )
    p.add_argument(
        "--list", action="store_true", dest="list_events",
        help="List events in the file and exit (no plotting).",
    )
    p.add_argument(
        "--no-ppg-resp", action="store_true",
        help="Only show ECG leads, skip PPG and respiratory plots.",
    )
    return p


def read_vitals(vitals_grp: h5py.Group) -> dict[str, str]:
    """Read vitals from HDF5 group into display-friendly strings."""
    info = {}
    for name in ["HR", "Pulse", "SpO2", "Systolic", "Diastolic", "RespRate", "Temp"]:
        if name in vitals_grp:
            val = vitals_grp[f"{name}/value"][()]
            units_raw = vitals_grp[f"{name}/units"][()]
            units = units_raw.decode("utf-8") if isinstance(units_raw, bytes) else str(units_raw)
            info[name] = f"{val} {units}"
    return info


def list_events(filepath: str) -> None:
    """Print a summary of all events in the HDF5 file."""
    with h5py.File(filepath, "r") as hf:
        # Patient info
        patient_id = "?"
        if "metadata" in hf and "patient_id" in hf["metadata"]:
            pid = hf["metadata/patient_id"][()]
            patient_id = pid.decode("utf-8") if isinstance(pid, bytes) else str(pid)

        event_keys = sorted(k for k in hf.keys() if k.startswith("event_"))
        print(f"File: {filepath}")
        print(f"Patient: {patient_id}")
        print(f"Events: {len(event_keys)}")
        print()
        print(f"  {'Event':<12s} {'Condition':<28s} {'HR':>5s} {'SpO2':>6s} {'BP':>10s} {'RR':>4s}")
        print("  " + "-" * 68)

        for ek in event_keys:
            grp = hf[ek]
            event_id = ek.replace("event_", "")

            cond_val = grp.attrs.get("condition", "?")
            if isinstance(cond_val, bytes):
                cond_val = cond_val.decode("utf-8")
            cond_name = _CONDITION_NAMES.get(cond_val, cond_val)

            hr = sp = bp = rr = "—"
            if "vitals" in grp:
                vg = grp["vitals"]
                if "HR" in vg:
                    hr = str(int(vg["HR/value"][()]))
                if "SpO2" in vg:
                    sp = f"{int(vg['SpO2/value'][()])}%"
                if "Systolic" in vg and "Diastolic" in vg:
                    bp = f"{int(vg['Systolic/value'][()]  )}/{int(vg['Diastolic/value'][()])}"
                if "RespRate" in vg:
                    rr = str(int(vg["RespRate/value"][()]))

            print(f"  {event_id:<12s} {cond_name:<28s} {hr:>5s} {sp:>6s} {bp:>10s} {rr:>4s}")


def plot_event(
    hf: h5py.File,
    event_key: str,
    filepath: str,
    save_path: str | None = None,
    show_ppg_resp: bool = True,
) -> None:
    """Plot a single event: 7-lead ECG + optional PPG/RESP + vitals annotation."""
    grp = hf[event_key]
    event_id = event_key.replace("event_", "")

    # Read condition
    cond_val = grp.attrs.get("condition", "?")
    if isinstance(cond_val, bytes):
        cond_val = cond_val.decode("utf-8")
    cond_name = _CONDITION_NAMES.get(cond_val, cond_val)
    hr_val = grp.attrs.get("heart_rate", None)

    # Read ECG leads
    ecg_grp = grp["ecg"]
    ecg_signals = {}
    for lead in LEAD_NAMES:
        if lead in ecg_grp:
            ecg_signals[lead] = ecg_grp[lead][:]

    if not ecg_signals:
        print(f"  [!] No ECG leads found in {event_key}")
        return

    n_ecg = len(list(ecg_signals.values())[0])
    t_ecg = np.arange(n_ecg) / FS_ECG

    # Read PPG / RESP
    ppg_signal = None
    resp_signal = None
    if show_ppg_resp:
        if "ppg" in grp and "PPG" in grp["ppg"]:
            ppg_signal = grp["ppg/PPG"][:]
        if "resp" in grp and "RESP" in grp["resp"]:
            resp_signal = grp["resp/RESP"][:]

    # Read vitals for annotation
    vitals_text = ""
    if "vitals" in grp:
        vitals = read_vitals(grp["vitals"])
        parts = []
        if "HR" in vitals:
            parts.append(f"HR: {vitals['HR']}")
        if "SpO2" in vitals:
            parts.append(f"SpO2: {vitals['SpO2']}")
        if "Systolic" in vitals and "Diastolic" in vitals:
            parts.append(f"BP: {vitals['Systolic'].split()[0]}/{vitals['Diastolic']}")
        if "RespRate" in vitals:
            parts.append(f"RR: {vitals['RespRate']}")
        if "Temp" in vitals:
            parts.append(f"Temp: {vitals['Temp']}")
        vitals_text = "  |  ".join(parts)

    # Determine layout
    n_leads = len(ecg_signals)
    extra_rows = 0
    if ppg_signal is not None:
        extra_rows += 1
    if resp_signal is not None:
        extra_rows += 1
    total_rows = n_leads + extra_rows

    fig_height = max(8, 1.6 * total_rows)
    fig = plt.figure(figsize=(16, fig_height), constrained_layout=False)
    gs = GridSpec(total_rows, 1, figure=fig, hspace=0.4, top=0.94, bottom=0.04)

    # Title
    title = f"Event {event_id}  —  {cond_name}"
    if hr_val is not None:
        title += f"  (HR: {hr_val:.0f} bpm)"
    fig.suptitle(title, fontsize=13, fontweight="bold", y=0.99)

    # Vitals subtitle
    if vitals_text:
        fig.text(0.5, 0.965, vitals_text, ha="center", fontsize=9, color="#555555")

    # Plot ECG leads
    for i, lead in enumerate(LEAD_NAMES):
        if lead not in ecg_signals:
            continue
        ax = fig.add_subplot(gs[i])
        ax.plot(t_ecg, ecg_signals[lead], linewidth=0.5, color="#1a1a2e")
        ax.set_ylabel(lead, fontsize=9, rotation=0, labelpad=35, ha="right")
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=7)
        if i < n_leads - 1 and extra_rows == 0:
            ax.set_xticklabels([])

    row_idx = n_leads

    # Plot PPG
    if ppg_signal is not None:
        n_ppg = len(ppg_signal)
        t_ppg = np.arange(n_ppg) / FS_PPG
        ax = fig.add_subplot(gs[row_idx])
        ax.plot(t_ppg, ppg_signal, linewidth=0.6, color="#e94560")
        ax.set_ylabel("PPG", fontsize=9, rotation=0, labelpad=35, ha="right")
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=7)
        row_idx += 1

    # Plot RESP
    if resp_signal is not None:
        n_resp = len(resp_signal)
        t_resp = np.arange(n_resp) / FS_RESP
        ax = fig.add_subplot(gs[row_idx])
        ax.plot(t_resp, resp_signal, linewidth=0.6, color="#0f3460")
        ax.set_ylabel("RESP", fontsize=9, rotation=0, labelpad=35, ha="right")
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=7)
        row_idx += 1

    # X-axis label on last subplot
    fig.axes[-1].set_xlabel("Time (s)", fontsize=9)

    # File info annotation
    fig.text(
        0.01, 0.005,
        f"{Path(filepath).name}  /  {event_key}",
        fontsize=7, color="#999999",
    )

    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"  Saved: {save_path}")
    else:
        plt.show()
        plt.close()


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    filepath = args.file
    if not Path(filepath).exists():
        print(f"Error: file not found: {filepath}")
        sys.exit(1)

    if args.list_events:
        list_events(filepath)
        return

    # Determine which events to plot
    with h5py.File(filepath, "r") as hf:
        all_event_keys = sorted(k for k in hf.keys() if k.startswith("event_"))

        if not all_event_keys:
            print(f"No events found in {filepath}")
            return

        if args.event:
            event_keys = [f"event_{eid}" for eid in args.event]
            missing = [ek for ek in event_keys if ek not in hf]
            if missing:
                print(f"Error: events not found: {', '.join(missing)}")
                print(f"Available: {', '.join(all_event_keys)}")
                sys.exit(1)
        else:
            event_keys = all_event_keys

        # Save dir setup
        save_dir = None
        if args.save_dir:
            save_dir = Path(args.save_dir)
            save_dir.mkdir(parents=True, exist_ok=True)
            # Use Agg backend for saving
            matplotlib.use("Agg")

        stem = Path(filepath).stem
        print(f"Plotting {len(event_keys)} event(s) from {Path(filepath).name}")

        for ek in event_keys:
            save_path = None
            if save_dir:
                event_id = ek.replace("event_", "")
                save_path = str(save_dir / f"{stem}_{ek}.png")

            plot_event(
                hf, ek, filepath,
                save_path=save_path,
                show_ppg_resp=not args.no_ppg_resp,
            )


if __name__ == "__main__":
    main()
